export enum AuditAction {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_PRIORITY_CHANGED = 'TASK_PRIORITY_CHANGED',
  TASK_ASSIGNEE_CHANGED = 'TASK_ASSIGNEE_CHANGED',
  TASK_DELETED = 'TASK_DELETED',
}
