server {
    listen 80;

    # Frontend (Next.js)
    location / {
        proxy_pass http://frontend:3000;
    }

    # Backend (NestJS API)
    location /api {
        proxy_pass http://backend:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}